name: Dependency Review
on: [pull_request]
name: 'Dependency Review'
permissions:read-all
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/dependency-review-action@v3
