name: HLint
permissions: read-all

on:
  push:

jobs:
  hlint:
    name: Scan code with HLint
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results.
      security-events: write
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: haskell-actions/hlint-scan@f9b967f4acb2a4ec0135d74e169ab8eb3494f15d # v0
