name: Ormolu
permissions: read-all

on:
  push:
    paths:
      - '**.hs'
      - '**.lhs'

jobs:
  ormolu:
    name: Ormolu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: haskell-actions/run-ormolu@71e9a598a0418f521508102528c6dd95915b62ef # v16
        with:
          respect-cabal-files: false
          extra-args: '-o -XGHC2021 -o -XOverloadedStrings'
