name: Ormolu
permissions: read-all

on:
  push:
    paths:
      - '**.hs'
      - '**.lhs'

jobs:
  ormolu:
    name: Ormolu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: haskell-actions/run-ormolu@51664d3a0b156e654b41bcdef917586d5207777f # v13
        with:
          respect-cabal-files: false
          extra-args: '-o -XGHC2021 -o -XOverloadedStrings'
